### ISSUE TITLE
Go memory problems on WinXP

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cef2go#6]
Binary example doesn't work anymore on WinXP after installing Windows Updates.

Issue reported to the Go project:

"Windows XP: "panic before malloc heap initialized" after installing Windows Updates"
https://code.google.com/p/go/issues/detail?id=7284

**Comment by z505** [comment]
what happens if the render processes are made in C inside go and only C? Does go still start its runtime/link its runtime into the exe and the garbage collector and everything, if you just have a C program inside go and nothing else?  

Still, even if you could trick go into not pulling in the garbage collector and make a C exe, it seems like kind of a hack and not really solving the issue. And, if you write a go program that is only C code, might as well just use GCC instead of go... but, with go using C, you at least can just compile it as usual with Go and not make a separate GCC/C file.

**Comment by cztomczak** [comment]
CEF can run sub-processes (Renderer, GPU, etc) using a separate executable, thus C++ could be used to create such executable. Most of CEF API is available in the Browser process. There is some CEF API available only in the Renderer process like some handlers and callbacks and DOM API (limited), but this still can be exposed using IPC messaging. Currently CEF2go doesn't expose any Renderer process API, so it wouldn't make a difference whether sub-process is run using Go or C++. 

Regarding essence of the issue, I don't think CEF2go should support Windows XP. Right now this OS has less then 5% usage share on desktop [1].

[1] https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers

**Comment by cztomczak** [comment]
Latest Chrome/CEF don't even support Windows XP / Vista anymore. So after upgrade to latest CEF it won't be possible to support this OS. So closing.
